### ISSUE TITLE
remove focus from the tab

### ISSUE THREAD

**Issue by programerr01** [kkapuria3/BestBuy-GPU-Bot#26]
Is there any way for the screen to not pull focus from other tabs and re-opening the tab itself?

**Comment by kkapuria3** [comment]
does running it in separate window help ?

**Comment by programerr01** [comment]
> does running it in separate window help ?

unfortunately, no.it forced focus on the new refresh

**Comment by kkapuria3** [comment]
**One of the quick fixes here would be to comment lines of code that creates new tabs at every refresh.** 

In order to do this quickly,
comment all the lines with : 

```
window.open(window.location.href, '_blank');
window.close();
```
and remove comments for all the lines with : 

`location.reload()`


this will make the bot refresh in the same tab. 

_**Please note:**_
The reason we don't use `location.reload()` is because it causes memory leak; which means when you are running bot for long time, your memory will slowly be utilized to 90-99% (by your browser) and cause your system to lag.

**Comment by programerr01** [comment]
thanks bro, i will try and let you know how it goes

**Comment by zdragonite21** [comment]
I found that running this in an incognito tab reduces the amount of memory leak. I'm not entirely sure though, just a thought.
