### ISSUE TITLE
"Verify Your Accout" Blue Button

### ISSUE THREAD

**Issue by athenawisdoms** [kkapuria3/BestBuy-GPU-Bot#29]
Hello, I have a questoin regarding the handling of the "Verify Your Account" button

1. Isn't `rgb(0, 70, 190)` the blue color of the "Verify Your Account" button, but the comments say the button changes to yellow so lets click it again?

```js
if (MainButtonColor === 'rgb(255, 224, 0)' || MainButtonColor === 'rgb(0, 70, 190)') {
    // Color of Button Changes to yellow then click again
    let ATC_Color = window.getComputedStyle(InStockButton[0]).backgroundColor;
    // When button turns yellow, we scream bagged !
     console.log("Add to Cart is available:" + ATC_Color + " | Lets Bag This ! ");
```

2. Whats the difference between `ATCYellowButton_L1` and `ATCYellowButton_L2`?
```js
 const ATCYellowButton_L1 = "btn btn-primary btn-lg btn-block btn-leading-ficon add-to-cart-button"
 const ATCYellowButton_L2 = "c-button c-button-primary c-button-lg c-button-block c-button-icon c-button-icon-leading add-to-cart-button"
```

3. Similarly, whats the difference between `GotoCartButton_L1` and `GotoCartButton_L2`?
```js
const GotoCartButton_L1 = "c-button c-button-secondary btn btn-secondary btn-sm c-button-sm btn-block c-button-block"
const GotoCartButton_L2 = "c-button c-button-secondary c-button-sm c-button-block "
```

**Comment by kkapuria3** [comment]
Hi @athenawisdoms 

L1 and L2 are what we internally denote as `class layers`. Sometimes BB changes the CSS classes for Verify Button (and other buttons) from their backend updates. There are also cases where class names differ between products. Hence, in order to address this change, we use `class layers`.. simply meaning if one CSS class name is not found then use another.

Hope this answers your question.
